#!/usr/bin/env python3
"""Combine a normalized ChatGPT digest with current state and private seed.

This script does not make semantic decisions. It builds a packet for an LLM/agent
that can reconcile history under the repository's precedence rules.
"""
from __future__ import annotations
import argparse
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def add_file(chunks, label, path):
    path = Path(path)
    if path.exists() and path.is_file():
        try:
            shown = path.relative_to(ROOT)
        except ValueError:
            shown = path
        chunks += ["", f"---\n\n# {label}: `{shown}`\n", path.read_text(encoding="utf-8", errors="replace")]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("digest", type=Path, help="normalized digest generated by ingest_chatgpt_export.py")
    ap.add_argument("--seed-dir", type=Path, default=ROOT / "research/private/idea_seed")
    ap.add_argument("--out", type=Path, default=ROOT / "research/private/reconciliation_packet.md")
    args = ap.parse_args()

    if not args.digest.exists():
        raise SystemExit(f"Digest not found: {args.digest}")

    chunks = [
        "# ChatGPT History Reconciliation Packet",
        "",
        "> Generated locally. Do not commit by default.",
        "",
    ]
    add_file(chunks, "RECONCILIATION INSTRUCTIONS", ROOT / ".workflow/prompts/reconcile_chatgpt_history.md")
    for p in [
        ROOT / "research/idea/current.md",
        ROOT / "research/idea/rejected.md",
        ROOT / "research/idea/open_questions.md",
        ROOT / "research/idea/decision_log.md",
    ]:
        add_file(chunks, "PUBLIC STATE", p)
    if args.seed_dir.exists():
        for p in sorted(args.seed_dir.glob("*")):
            if p.is_file() and p.suffix.lower() in {".md", ".json", ".txt"}:
                add_file(chunks, "PRIVATE SEED", p)
    add_file(chunks, "NORMALIZED CHATGPT HISTORY", args.digest)

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(chunks), encoding="utf-8")
    print(f"Wrote {args.out}")

if __name__ == "__main__":
    main()
